package com.nhlstenden.windturbines;

import java.util.HashSet;

public class EnergyRoom {
    private HashSet<Windturbine> windturbines;
    private Heatpump heatpump;
    private SmartController smartController;
    private int windSpeed; // in meters per second

    public EnergyRoom(Heatpump heatpump, SmartController smartcontroller) {
        this.heatpump = heatpump;
        this.smartController = smartcontroller;
        this.windturbines = new HashSet<>();
    }

    public HashSet<Windturbine> getWindturbines() {
        return this.windturbines;
    }

    public void addWindturbines(Windturbine windturbine) {
        this.windturbines.add(windturbine);
    }

    public Heatpump getHeatpump() {
        return this.heatpump;
    }

    public void setHeatpump(Heatpump heatpump) {
        this.heatpump = heatpump;
    }

    public SmartController getSmartController() {
        return this.smartController;
    }

    public void setSmartController(SmartController smartController) {
        this.smartController = smartController;
    }

    public int getWindSpeed() {
        return this.windSpeed;
    }

    public void setWindSpeed(int windSpeed) {
        this.windSpeed = windSpeed;
    }

    /**
     * Calculate and return the amount of heat generated by the heatpump
     * @param windSpeed
     * @return The amount of heat generated by the heatpump
     */
    public double calcGeneratedHeat(int windSpeed) {
        return this.heatpump.generateHeat();
    }
}
